language: c

branches:
  only:
    - it2

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc

      python: 2.7.7

      addons:
        apt:
          sources:
            - deadsnakes
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - valgrind
            - cppcheck
            - gcc-7
            - g++-7

before_install:
  - sudo -H pip install --upgrade requests[security]
  - sudo apt-get -y install valgrind

script:
    # скрипт сборки и тестирования проекта:
    - export CXX=/usr/bin/g++-7
    - export C=/usr/bin/gcc-7
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
    - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ctest
    - cd ..
    - cppcheck --inconclusive --enable=all --language=c src/*.c libs/*.c
