language: c

os:
    - linux

compiler:
    - gcc
    - clang

install:
    # скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
    - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ctest
    - cd ..
    - cppcheck --inconclusive --enable=all --language=c libs/*.c src/*.c
after_success:
    - coveralls --root .. --build-root . -E ".*CMakeFiles.*" -E ".*googletest*" --gcov /usr/bin/gcov --gcov-options '\-lp' 

