sudo:     required  # используем Virtual Machine

language: c

os:
    - linux

compiler:
    - gcc

env:
    # список переменных окружения, влияющих на матрицу сборки:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

install:
    # скрипт настройки среды и установки зависимостей:
    - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest
    - valgrind --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ctest
    - cd ../src
    - cppcheck --inconclusive --enable=all --language=c main.c task_one.c
after_success:
    - coveralls --root .. --build-root . -E ".*CMakeFiles.*" -E ".*googletest*" --gcov /usr/bin/gcov --gcov-options '\-lp' 

